name: Android Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    name: Unit Test
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup jdk
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"

      - name: permission
        run: chmod +x ./gradlew

      - name: execute unit test
        run: ./gradlew testDebugUnitTest

      - name: test report
        run: ./gradlew jacocoDebugUnitTest

      - name: merge report
        run: ./gradlew koverMergedReport

      - name: upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
